pdf:
	pdflatex ollie-optimization.tex
	bibtex ollie-optimization.aux
	pdflatex ollie-optimization.tex
	pdflatex ollie-optimization.tex
clean:
	rm -rf *.blg *.out *.fdb_latexmk *.aux *.fls *.synctex.gz *.bbl  *.log
